### Logout
GET http://localhost:3000/logout HTTP/1.1

### get my user
GET http://localhost:3000/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTExNDk0NWU0OTc0ZTJkNjU2MzYzOTciLCJpYXQiOjE2Mjg1MjMxODQwMzMsImV4cCI6MTYyODUyMzI3MDQzM30.E3cYdp1bG2XBEM0_hWPutu3cGUSfrjzwkEi-OrFI7s3ApUVOGSKv87WCpU9SIrDH6eGPKG_UjCYrjF6T8mGVcU7smfKlF9uScFVCbRJ7BQJ5XQehx7mD0VQaH0S-8n7LdM20pcntNoDiM_FUm2ovM6iIKsZ6QZS73wNCuNIdykBcQnHzhOOExaJJiiaCJ0z4qqxYPTc8I40zCpc3fyH9GiCl2wr4foXEvdCiVi6B0TFMMAmTxZCulnR3nyOPmYMbIMTocFTaGpNMnWOGP7miOeR4ANGyPdIE2gUtIg92bnUdTdsPK7_BBIk4-AM2LJsFgJdRMa9gT_MYHu2gs7VigMbWekUSQGmNM6sadtFAXd5t17i-DWxgKKOmatJb8jHvhY2VA-d3iqKx_A7OqpVEanJOZhK4IKDCQGiFK5CD3QEo2QiDcdI3XPWPnDEddml8xTrSmTuXzfyrda9edmk6uTEx4LsU1pIXoM4U5tDaTnUvEKnuvvD2FZ0615SxnoF54WwZ3-xMxAKAnN5aDlqDfUB6KW_KCf8GwgpkQfFiU46-Wc_0bkOkvcC5Udswp6eBOOSTASFbTCis9gpuUbN655BvoMsrvCxXlx-ERpX3BKdzAs44fQBSVIlwsJzgPY9HuDm3LOkLtJzlP5OJJ6PV_PGh1No6f3whFveiGY6nmK4


### Register
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "matest",
    "password": "1234"
}

### Login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "matest",
    "password": "1234"
}
